name: file_parser-ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APPLICATION_PORT: 3000
  APPLICATION_HOST: file_parser_api

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true
      - name: Check ruby version
        run:  |
          ruby -v
          which ruby
          gem install bundler
      - name: Install gems
        run: |
          bundle config set --local deployment true
          bundle install -j $(nproc)
      - name: Create temporary env files
        run: |
          mv .env-example .env
      - name: Check the application code
        run: |
          RAILS_ENV=production bundle exec rails routes
      - name: Run lint
        run: |
          RAILS_ENV=test bundle exec rubocop -d

  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true
      - name: Check ruby version
        run:  |
          ruby -v
          which ruby
          gem install bundler
      - name: Install gems
        run: |
          bundle config set --local deployment true
          bundle install -j $(nproc)
      - name: Create temporary env files
        run: |
          mv .env-example .env
      - name: Check the application code
        run: |
          RAILS_ENV=production bundle exec rails routes
      - name: Run lint
        run: |
          RAILS_ENV=test bundle exec rspec spec --fail-fast=1 --format d
